### Site info:
title: jeremyrunyan.me
tagline:
author: Jeremy Runyan
email: googlebot42@gmail.com
description: "Jeremy Runyan's Homepage" # You can edit this line in _config.yml. It will appear in your document head meta and in your feed.xml site description
keywords: "Matthew Jeremy Runyan GoogleBot GoogleBot42"
#baseurl: "/freshman21" # the subpath of your site, e.g. /blog
#url: "http://yulijia.net/freshman21" # the base hostname & protocol for your site
locale: en_US

### Personal info and site tools info:
twitter_username: googlebot42
github_username:  GoogleBot42
disqus_shortname: JeremyRunyan
favicon:     "/images/favicon.ico"
aboutme: Hello, I am Jeremy Runyan. This is my website/blog. It currently underconstruction so there is nothing to see yet.
aboutme_photo: /images/me.jpg # your photo.


### Site setting:
ShowContactInfo: "True" # Personal Info (twitter,github,email) can be seen on aboutme-sidebar, those info only shown when ShowContactInfo == True
default_column: "two" # blog style: two columns, if default_column != "two", you will see a one column blog.
default_locale: "en" # blog sidebar language set, only include: English(en) and Chinese (cn)

locales:
    en:
      Aboutme: "About Me"
      Archives: "Archives"
      Blogroll: "Blogroll"
      Categories: "Categories"
      Copyright_Notice: "Copyright Notice"
      Recent_Posts: "Recent Posts"
      Tags: "Tags"
      Previous: "Older"
      Next: "Newer"
      PostedInCategories: "Posted in"
      Taggedwith: "and tagged"
      PostDate: "on "
    cn:
      Aboutme: "关于我"
      Archives: "存档"
      Blogroll: "良师益友"
      Categories: "分类目录"
      Copyright_Notice: "版权声明"
      Recent_Posts: "近期文章"
      Tags: "标签"
      Previous: "前一页"
      Next: "后一页"
      PostedInCategories: "目录:"
      Taggedwith: "| 标签:"
      PostDate: "| 发表时间: "


### your Blogroll info, only name can shown on the page.

Blogroll:
    - name: GoogleBot42's website # TODO: better name
      href: googlebot42.github.io
      title: Jeremy Runyan's Blog


### Build settings
markdown: kramdown
highlighter: pygments
paginate: 5
