### Site info:
title: jeremyrunyan.me
tagline:
author: Jeremy Runyan
email: contact@jeremyrunyan.me
description: "Jeremy Runyan's Homepage"
keywords: "Matthew Jeremy Runyan GoogleBot GoogleBot42"
#baseurl: "/freshman21" # the subpath of your site, e.g. /blog
url: "http://jeremyrunyan.me"
locale: en_US

### Personal info and site tools info:
twitter_username: googlebot42
github_username:  GoogleBot42
disqus_shortname: jeremyrunyan-me
#favicon:     "/images/favicon.ico"
aboutme: Hello, I am Jeremy Runyan. This is my website and blog. It is relatively new so there isn't much here yet."
aboutme_photo: /images/me.jpg # your photo.


### Site setting:
ShowContactInfo: "True" # Personal Info (twitter,github,email) can be seen on aboutme-sidebar, those info only shown when ShowContactInfo == True
default_column: "two" # blog style: two columns, if default_column != "two", you will see a one column blog.
default_locale: "en"

locales:
    en:
      Aboutme: "About Me"
      Archives: "Archives"
      Blogroll: "Blogroll"
      Categories: "Categories"
      Copyright_Notice: "Copyright Notice"
      Recent_Posts: "Recent Posts"
      Tags: "Tags"
      Previous: "Older"
      Next: "Newer"
      PostedInCategories: "Posted in"
      Taggedwith: "and tagged"
      PostDate: "on "


### Build settings
markdown: kramdown
highlighter: pygments
paginate: 5
